# Generated by Django 5.2.8 on 2026-01-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=200)),
                ('requests', models.IntegerField(default=0)),
                ('main', models.CharField(blank=True, max_length=200)),
                ('shortened', models.CharField(blank=True, max_length=200)),
                ('useragent', models.CharField(blank=True, max_length=200)),
                ('link_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
