# Generated by Django 5.2.8 on 2026-01-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='main',
            new_name='main_link',
        ),
    ]
